FROM node:18-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn build && \
        yarn run build && \
        yarn cache clean

FROM nginx:1.17.8

COPY --from=build /app/build/ /usr/share/nginx/html
COPY --from=build /app/public/ /usr/share/nginx/html
COPY --from=build /app/build/ /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf

EXPOSE 5000
CMD ["nginx", "-g", "daemon off;"]